### ISSUE TITLE
TLS Options are not available with labels

### ISSUE THREAD

**Issue by m0rtalis** [javabean/Dockerfiles#1]
https://github.com/javabean/Dockerfiles/blob/fc8039589535c8a76e0afd11d8537a2395ac7a43/docker-compose.yml#L115-L116

TLS Options are only available with the file provider.

> Restriction
> 
> In the above example, we've used the file provider to handle these definitions. It is the only available method to configure the certificates (as well as the options and the stores). However, in Kubernetes, the certificates can and must be provided by secrets.
> 

https://docs.traefik.io/v2.1/https/tls/

**Comment by javabean** [comment]
Good catch! I will comment out those lines until Traefik improves in regard to Docker labels configuration.
